config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :mobiles
    resources :delars
    root to: "users#index"
  end
  get 'mobile/:mobile_id/:mobile_name' => 'visitors#mobile_show', :as => :view_mobile
  get 'send_sms' => 'visitors#send_sms'
  root to: 'visitors#index'
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users
end

app/models/delar.rb
class Delar < ActiveRecord::Base
  has_and_belongs_to_many :mobiles, :join_table => :mobiles_delars
end

app/models/mobile.rb
class Mobile < ActiveRecord::Base
  has_and_belongs_to_many :delars, :join_table => :mobiles_delars
  has_attached_file :image, styles: { medium: "800x300>", thumb: "3200x150>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_filters.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_filter :authenticate_admin

    def authenticate_admin
      # TODO Add authentication logic here.
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/delars_controller.rb
module Admin
  class DelarsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Delar.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Delar.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/mobiles_controller.rb
module Admin
  class MobilesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Mobile.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Mobile.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :contact_number, :address, :city, :state, :country, :pincode, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :contact_number, :address, :city, :state, :country, :pincode, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only, :except => :show

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to :back, :alert => "Access denied."
      end
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def admin_only
    unless current_user.admin?
      redirect_to :back, :alert => "Access denied."
    end
  end

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def index
    if user_signed_in?
      if params['delar_city'].present?
        delars = Delar.where(:city => params['delar_city'])
      elsif current_user.city.present?
        delars = Delar.where(:city => current_user.city)
      end
    elsif params['delar_city'].present?
      delars = Delar.where(:city => params['delar_city'])
    end
    if request.xhr?
      @mobiles =if params['mobile'].present?
                  if delars.present?
                    Mobile.joins(:mobiles_delars).where(mobile_params).where(["mobiles_delars.delar_id IN (?)", delars.map(&:id)]).uniq
                  else
                    Mobile.where(mobile_params).uniq
                  end
                else
                  if delars.present?
                    Mobile.joins(:mobiles_delars).where(["mobiles_delars.delar_id IN (?)", delars.map(&:id)]).uniq
                  else
                    Mobile.all.uniq
                  end
                end

      render :partial => 'visitors/thumb_mobile', :collection => @mobiles,  :as => :mobile, :layout => false
    else
      @mobiles = if delars.present?
                   Mobile.joins(:mobiles_delars).where(["mobiles_delars.delar_id IN (?)", delars.map(&:id)]).uniq
                 else
                   Mobile.all.uniq
                 end
    end
  end

  def mobile_show
    @mobile = Mobile.find(params[:mobile_id])
  end

  def send_sms
    delar = Delar.find(params[:delar_id])
    msg = "Hi #{delar.name}, Contact Me: #{current_user.name}, Mobile No: #{current_user.contact_number}"
    @client = Twilio::REST::Client.new
    @client.account.messages.create({:to => "+91#{delar.contact}", :from => '+12018796790', :body => msg})
    render :json => {:success => true}
  end

  private

  def mobile_params
    params.require(:mobile).permit({:brand_name => []}, {:mobile_type => []}, {:battery_capacity => []}, {:screen_size => []},
                                   {:ram => []}, {:sim_type => []}, {:primary_camera => []}, {:os_version_name => []}, {:secondary_camera => []},
                                   {:features => []}, {:number_of_cores => []})
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_delars_message
    if user_signed_in?
      if current_user.city.present?
        if delars_exist?
          "( #{current_user.city.capitalize} delars )"
        else
          "(In your city we don't have delars. So we are showing all our delars.)"
        end
      else
        "(Add city in your account to get delars for your city.)"
      end

    else
      "(All delars)"
    end
  end

  def delars_exist?
    delars = Delar.where(:city => current_user.city)
    if delars.present?
      mobiles_count = Mobile.joins(:mobiles_delars).where(["mobiles_delars.delar_id IN (?)", delars.map(&:id)]).count
      mobiles_count > 0
    else
      false
    end
  end
end

app/views/fields/image_field/_form.html.erb
<div class="field-unit__label">
  <%= f.label field.attribute %>
</div>
<div class="field-unit__field">
  <%= f.file_field field.attribute %>
</div>

app/views/fields/image_field/_index.html.erb
<%= image_tag field.thumbnail %>

app/views/fields/image_field/_show.html.erb
<%= image_tag field.url %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <li><%= link_to 'Admin', '/admin' %></li>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Online Mobile Sales" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Online Mobile Sales" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
    <div class="row">
      <div class="col-md-4">
        <img src="/iPhone-icon.png" />
      </div>
      <div class="col-md-8">
        <% content_for :title do %>About<% end %>
        <h3>About the Website</h3>
        <p>
          The main use of this website is the customer can easily search details of the

          mobile in which customer is willing to buy he can do all this from home by

          registering to the online mobile services, he gets email alerts on special occasions

          regarding offers, so that it will be easy to the customer to buy.
        </p>
      </div>
    </div>
</div>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/_thumb_mobile.html.erb
<div class="col-sm-4 col-lg-4 col-md-4">
  <div class="thumbnail">
    <%= link_to image_tag(mobile.image.url(:thumb)), view_mobile_path(mobile.id, mobile.mobile_name) %>
    <div class="caption">
      <h4 class="pull-right">Rs.<%= mobile.price %></h4>
      <h4><a href="<%= view_mobile_path(mobile.id, mobile.mobile_name) %>" class="caption-title"><%= mobile.mobile_name %></a>
      </h4>
    </div>
  </div>
</div>

app/views/visitors/index.html.erb
<!-- Page Content -->
<div class="container">

    <div class="row">
      <form id="filter">
        <div class="col-md-3">
            <p class="lead">Online Mobile Sales & Services</p>
            <span><%= get_delars_message() %></span>
            <br/>
            <br/>
          <h4>Delars City</h4>
          <div class="list-group">
            <% Delar.all.map(&:city).uniq.each do |city| %>
                <li class="list-group-item">
                  <input type="checkbox" name="delar_city[]" value="<%= city %>"> <span><%= city %></span>
                </li>
            <% end %>
          </div>
            <h4>BRAND</h4>
            <div class="list-group">
              <% @mobiles.map(&:brand_name).uniq.each do |brand_name| %>
                  <li class="list-group-item">
                    <input type="checkbox" name="mobile[brand_name][]" value="<%= brand_name %>"> <span><%= brand_name %></span>
                  </li>
              <% end %>
            </div>

          <h4>MOBILE TYPE</h4>
          <div class="list-group">
            <% @mobiles.map(&:mobile_type).uniq.each do |mobile_type| %>
                <li class="list-group-item">
                  <input type="checkbox" name="mobile[mobile_type][]" value="<%= mobile_type %>"> <span><%= mobile_type %></span>
                </li>
            <% end %>
          </div>

          <h4>BATTERY CAPACITY</h4>
          <div class="list-group">
            <% @mobiles.map(&:battery_capacity).uniq.each do |battery_capacity| %>
                <li class="list-group-item">
                  <input type="checkbox" name="mobile[battery_capacity][]" value="<%= battery_capacity %>"> <span><%= battery_capacity %></span>
                </li>
            <% end %>
          </div>

          <h4>SCREEN SIZE</h4>
          <div class="list-group">
            <% @mobiles.map(&:screen_size).uniq.each do |screen_size| %>
                <li class="list-group-item">
                  <input type="checkbox" name="mobile[screen_size][]" value="<%= screen_size %>"> <span><%= screen_size %></span>
                </li>
            <% end %>
          </div>

          <h4>RAM</h4>
          <div class="list-group">
            <% @mobiles.map(&:ram).uniq.each do |ram| %>
                <li class="list-group-item">
                  <input type="checkbox" name="mobile[ram][]" value="<%= ram %>"> <span><%= ram %></span>
                </li>
            <% end %>
          </div>

          <h4>SIM TYPE</h4>
          <div class="list-group">
            <% @mobiles.map(&:sim_type).uniq.each do |sim_type| %>
                <li class="list-group-item">
                  <input type="checkbox" name="mobile[sim_type][]" value="<%= sim_type %>"> <span><%= sim_type %></span>
                </li>
            <% end %>
          </div>

          <h4>PRIMARY CAMERA</h4>
          <div class="list-group">
            <% @mobiles.map(&:primary_camera).uniq.each do |primary_camera| %>
                <li class="list-group-item">
                  <input type="checkbox" name="mobile[primary_camera][]" value="<%= primary_camera %>"> <span><%= primary_camera %></span>
                </li>
            <% end %>
          </div>

          <h4>OS VERSION NAME</h4>
          <div class="list-group">
            <% @mobiles.map(&:os_version_name).uniq.each do |os_version_name| %>
                <li class="list-group-item">
                  <input type="checkbox" name="mobile[os_version_name][]" value="<%= os_version_name %>"> <span><%= os_version_name %></span>
                </li>
            <% end %>
          </div>

          <h4>SECONDARY CAMERA</h4>
          <div class="list-group">
            <% @mobiles.map(&:secondary_camera).uniq.each do |secondary_camera| %>
                <li class="list-group-item">
                  <input type="checkbox" name="mobile[secondary_camera][]" value="<%= secondary_camera %>"> <span><%= secondary_camera %></span>
                </li>
            <% end %>
          </div>

          <h4>FEATURES</h4>
          <div class="list-group">
            <% @mobiles.map(&:features).uniq.each do |features| %>
                <li class="list-group-item">
                  <input type="checkbox" name="mobile[features][]" value="<%= features %>"> <span><%= features %></span>
                </li>
            <% end %>
          </div>

          <h4>NUMBER OF CORES</h4>
          <div class="list-group">
            <% @mobiles.map(&:number_of_cores).uniq.each do |number_of_cores| %>
                <li class="list-group-item">
                  <input type="checkbox" name="mobile[number_of_cores][]" value="<%= number_of_cores %>"> <span><%= number_of_cores %></span>
                </li>
            <% end %>
          </div>
        </div>
      </form>
        <div class="col-md-9">

            <div class="row carousel-holder">

                <div class="col-md-12">
                    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                        <ol class="carousel-indicators">
                            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                        </ol>
                        <div class="carousel-inner">
                          <% @mobiles.sample(3).each_with_index do |mobile, i|%>
                            <div class="item <%= 'active' if i == 0 %>">
                              <%= link_to image_tag(mobile.image.url(:medium)), view_mobile_path(mobile.id, mobile.mobile_name) %>
                            </div>
                          <% end %>
                        </div>
                        <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                            <span class="glyphicon glyphicon-chevron-left"></span>
                        </a>
                        <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                            <span class="glyphicon glyphicon-chevron-right"></span>
                        </a>
                    </div>
                </div>

            </div>

            <div class="row" id="thumb-mobile">
              <% @mobiles.each do |mobile| %>
                <%= render :partial => 'thumb_mobile', :locals => {:mobile => mobile}%>
              <% end %>

            </div>

        </div>

    </div>

</div>
<!-- /.container -->

<div class="container">

    <hr>

    <!-- Footer -->
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright &copy; Your Website 2014</p>
            </div>
        </div>
    </footer>

</div>
<!-- /.container -->

<script type="text/javascript">
  $('form input').on('change', function(){
      var data = $('form').serialize();
      $.ajax({
          url: '/',
          data: data,
          processData: false,
          type: 'GET',
          success: function ( data ) {
              console.log(data);
              $('#thumb-mobile').html(data);
          }
      });
  });
</script>

app/views/visitors/mobile_show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4" style="padding-top: 50px;">
      <%= image_tag @mobile.image.url(:medium) %>
    </div>
    <div class="col-md-4">
      <h3><%= @mobile.mobile_name %></h3>
      <dl class="dl-horizontal">
        <% skip_values = ['id', 'mobile_name', 'created_at', 'updated_at', 'image_file_name', 'image_content_type', 'image_file_size', 'image_updated_at']%>
        <% @mobile.attributes.each do |title, value|%>
          <% unless skip_values.include?(title) %>
            <dt><%= title.gsub('_', ' ').capitalize %></dt>
            <dd><%= 'Rs. ' if title == 'price' %><%= value %></dd>
          <% end %>
        <% end %>
      </dl>
    </div>
  </div>
  <div class="row">
      <h4>Delars:</h4>
      <% @mobile.delars.each do |delar| %>
        <div class="col-md-4">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title"><%= delar.name %></h3>
            </div>
            <% skip_values = ['id', 'name', 'address', 'created_at', 'updated_at']%>
            <div class="panel-body">
              <dl class="dl-horizontal" >
                <% delar.attributes.each do |title, value|%>
                    <% unless skip_values.include?(title) %>
                        <dt><%= title.gsub('_', ' ').capitalize %></dt>
                        <dd><%= value %></dd>
                    <% end %>
                <% end %>
              </dl>
            </div>
            <div class="panel-footer">
              <button type="button" class="btn btn-success" onclick="sendOutSms(<%= delar.id %>)" id="send_sms">Send SMS</button>
            </div>
          </div>
        </div>
      <% end %>
  </div>
</div>

<script type="text/javascript">
  function sendOutSms(delar_id){
      $('#send_sms').addClass('disabled');
      $.ajax('/send_sms?delar_id='+delar_id, {
          success: function(data) {
             alert("Sent Your details to delar. Will contact you soon.");
             $('#send_sms').removeClass('disabled');
          },
          error: function() {
              $('#send_sms').removeClass('disabled');
          }
      });
  }
</script>